// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3104.DDR3x104_Robot_Builder;

import org.usfirst.frc3104.DDR3x104_Robot_Builder.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.*;
import org.usfirst.frc3104.DDR3x104_Robot_Builder.subsystems.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton joystickButton5;
    public JoystickButton joystickButton6;
    public JoystickButton joystickButton7;
    public JoystickButton joystickButton8;
    public Joystick leftJoystick;
    public JoystickButton joystickButton1;
    public JoystickButton joystickButton2;
    public JoystickButton joystickButton3;
    public JoystickButton joystickButton4;
    public Joystick rightJoystick;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        rightJoystick = new Joystick(0);
        
        joystickButton4 = new JoystickButton(rightJoystick, 3);
        joystickButton4.whileHeld(new InteractiveBallIn());
        joystickButton3 = new JoystickButton(rightJoystick, 5);
        joystickButton3.whileHeld(new InteractiveBallOut());
        joystickButton2 = new JoystickButton(rightJoystick, 4);
        joystickButton2.whileHeld(new InteractiveLowerIntake());
        joystickButton1 = new JoystickButton(rightJoystick, 6);
        joystickButton1.whileHeld(new InteractiveRaiseIntake());
        leftJoystick = new Joystick(1);
        
        joystickButton8 = new JoystickButton(leftJoystick, 1);
        joystickButton8.whenPressed(new InteractiveBallOut());
        joystickButton7 = new JoystickButton(leftJoystick, 1);
        joystickButton7.whenPressed(new InteractiveBallIn());
        joystickButton6 = new JoystickButton(leftJoystick, 1);
        joystickButton6.whenPressed(new InteractiveLowerIntake());
        joystickButton5 = new JoystickButton(leftJoystick, 1);
        joystickButton5.whenPressed(new InteractiveRaiseIntake());


        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command Low Bar", new AutonomousCommandLowBar());
        SmartDashboard.putData("Autonomous Command Fast", new AutonomousCommandFast());
        SmartDashboard.putData("Autonoumous Command Slow", new AutonoumousCommandSlow());
        SmartDashboard.putData("Raise Intake", new RaiseIntake());
        SmartDashboard.putData("Lower Intake", new LowerIntake());
        SmartDashboard.putData("Drive", new Drive());
        SmartDashboard.putData("Interactive Raise Intake", new InteractiveRaiseIntake());
        SmartDashboard.putData("Interactive Lower Intake", new InteractiveLowerIntake());
        SmartDashboard.putData("Ball In", new BallIn());
        SmartDashboard.putData("Ball Out", new BallOut());
        SmartDashboard.putData("Interactive Ball In", new InteractiveBallIn());
        SmartDashboard.putData("Interactive Ball Out", new InteractiveBallOut());
        SmartDashboard.putData("Parallel Intake", new ParallelIntake());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getLeftJoystick() {
        return leftJoystick;
    }

    public Joystick getRightJoystick() {
        return rightJoystick;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

